spring.application.name=BotTelegram

meubot.telegram.token=SEU_TOKEN_AQUI
meubot.telegram.username=NOME_DO_SEU_BOT

meubot.ollama.url=http://localhost:11434/api/chat
meubot.ollama.model=llama3.2:1b
meubot.ollama.max-messages=10