spring.application.name=BotTelegram

meubot.telegram.token=MEU TOKEN
meubot.telegram.username=MEU TOKEN

meubot.ollama.url=http://localhost:11434/api/chat
meubot.ollama.model=llama3.2:1b
meubot.ollama.max-messages=10