spring.application.name=BotTelegram

meubot.telegram.token=8748659591:AAEYvMr9wqLMbs1fx16lTTVTHs0ygx1Iq9U
meubot.telegram.username=MeuBotLembrete

meubot.ollama.url=http://localhost:11434/api/chat
meubot.ollama.model=llama3.2:1b
meubot.ollama.max-messages=10